<Mygrid>
    GridLayout:
        cols:1

        GridLayout:
            cols:2
            Label:
                text: "Username: "
                font_size: 14
            TextInput:
                multiline: False
            Label:
                text: "Password"
                font_size:14
            TextInput:
                multiline: False
        Button:
            text: 'submit'
            font_size: 20